### ISSUE TITLE
question_answering_v2 data.csv导入不进去

### ISSUE THREAD

**Issue by LoveChina-3000** [zilliz-bootcamp/intelligent_question_answering_v2#1]
请问下,我安装readme 步骤操作后，bert服务启动了，查询服务也启动了。但是data.csv导入不进去。服务也没有报错。请教下，这个是什么问题呢

**Comment by Bennu-Li** [comment]
我们这边运行是正常的，请您确保能正常连接milvus，PostgreSQL以及 Bert 服务。其次保证所导入的数据集格式正确。下载的bert模型和数据集语言是一致的。
